### ISSUE TITLE
HTTP status 429 "Too many requests" for Wikimedia Maps

### ISSUE THREAD

**Issue by Tigerfell** [Firefishy/SimpleMap#4]
When viewing a wiki page with a map display, the Wikimedia map provided by this extension is missing. The map image returns HTTP status 429. To verify, visit any page that contains a map provided by this extension, for instance https://wiki.openstreetmap.org/wiki/Wiki:Maps.

**Comment by tomhughes** [comment]
Wikimedia have blocked all third parties from using their maps.

**Comment by tomhughes** [comment]
See https://phabricator.wikimedia.org/T245145#5880898 for details.

**Comment by Tigerfell** [comment]
I guess, there are three options now

- you make an arrangement with WMF
- finding a new map provider
- replacing this extension

Any preferences?

**Comment by tomhughes** [comment]
Well frankly I'm surprised this is using wikimedia maps and not our own maps?

**Comment by Tigerfell** [comment]
It uses tile stitching, I am not aware of openstreetmap.org providing a service like that. It used to use a service by FOSSGIS, but they blocked the wiki without prior notice a year ago, so @harry-wood switched this to WMF (#3).

**Comment by stephankn** [comment]
I reported this on the Wikimedia list, in the hope we can be on the allow-list.
https://lists.wikimedia.org/pipermail/maps-l/2020-September/001731.html

**Comment by stephankn** [comment]
While Wikimedia might find a solution to allow usage of their resources by OSM, it could take a while to clarify and outcome is not clear due to unclear affiliate status. See https://phabricator.wikimedia.org/T261694

I saw that the server of local chapter openstreetmap.de is now serving on https, which was the blocking point before. So could we simply switch back to OSM provided servers? I submitted PR #5 to fix.
